name: Deploy Website to S3

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to S3
      uses: aws-actions/s3-sync@v1
      with:
        bucket: ${{ secrets.AWS_S3_BUCKET }}
        region: ${{ secrets.AWS_REGION }}
        delete: true
        no-follow-symlinks: true
        path: .
        exclude: |
          *.md
          .github/*
          .git/*
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
